#!/bin/sh

# generated by https://github.com/jeffsanc/auto.git

export my_CUR_FOLDER=$(pwd);
echo "Going to ROS workspace folder:"$ROS_BUILDWS_NAME
cd ~/$ROS_BUILDWS_NAME && catkin build;
cd $my_CUR_FOLDER;
echo "Returning back to previous folder:":$my_CUR_FOLDER
